version: "3"

services:
  master:
    image: alpine-spark
    command:
      ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/conf
      - ./data:/data

  worker:
    image: alpine-spark
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://master:7077",
      ]
    hostname: worker
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    depends_on:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/conf
      - ./data:/data

  jupyter:
    image: alpine-spark
    command: jupyter notebook --ip 0.0.0.0 --allow-root --no-browser
    depends_on:
      - worker
    ports:
      - 8888:8888
    volumes:
      - ./src:/notebooks
      - ./data:/data
    working_dir: /notebooks
